// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR02eveH7vSVO5c9PinmoDprq4K9AeCmY',
    appId: '1:316394099784:android:5ada23b78654b6f58eb47d',
    messagingSenderId: '316394099784',
    projectId: 'idex-01',
    storageBucket: 'idex-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeO0qR0qM23PpL6sUGOP8gD6HHI82fSIQ',
    appId: '1:307197749550:ios:eb2a733ad826843bad32bf',
    messagingSenderId: '307197749550',
    projectId: 'ideasstorage-1',
    storageBucket: 'ideasstorage-1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeO0qR0qM23PpL6sUGOP8gD6HHI82fSIQ',
    appId: '1:307197749550:ios:eb2a733ad826843bad32bf',
    messagingSenderId: '307197749550',
    projectId: 'ideasstorage-1',
    storageBucket: 'ideasstorage-1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAePed6pHs15aQds0kasQDhDt6d_RCD2A',
    appId: '1:307197749550:web:2d8db4bd9aa5b98aad32bf',
    messagingSenderId: '307197749550',
    projectId: 'ideasstorage-1',
    authDomain: 'ideasstorage-1.firebaseapp.com',
    storageBucket: 'ideasstorage-1.firebasestorage.app',
    measurementId: 'G-774G0Y0GV7',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAePed6pHs15aQds0kasQDhDt6d_RCD2A',
    appId: '1:307197749550:web:5bafb50bfbacfa59ad32bf',
    messagingSenderId: '307197749550',
    projectId: 'ideasstorage-1',
    authDomain: 'ideasstorage-1.firebaseapp.com',
    storageBucket: 'ideasstorage-1.firebasestorage.app',
    measurementId: 'G-8T6P7B02E8',
  );
}
